<?php

namespace Udemy\Laravel\Model;

use Udemy\Laravel\Api\ApiInterface;
use Udemy\Laravel\Api\Course as Api;
use Illuminate\Support\Facades\Cache;

/**
 * Class Course
 *
 * @package Udemy\Laravel\Model
 *
 * @property string path
 * @property string title
 * @property string icon
 * @property string archived
 * @property string originalURL
 * @property string iphoneURL
 * @property string androidURL
 * @property string splitURL
 * @property string expiresAt
 * @property string expiredURL
 * @property string redirectType
 * @property string cloaking
 * @property string source
 * @property string AutodeletedAt
 * @property integer DomainId
 * @property-read string createdAt
 * @property-read string updatedAt
 * @property-read integer OwnerId
 * @property-read string secureShortURL
 * @property-read string shortURL
 */
class Course extends Model
{

    protected $fillable = Api::properties;

    public static function findByModel($model)
    {
//        return static::findByDomainAndPath($model->domain->hostname, $model->slug);
        return static::all()->filter(
            function ($link) use ($model) {
                return $link->id = $model->Udemy_id;
            }
        )->first();
    }

    static public function all()
    {
        $instance = (new static)->newInstance();

        return Cache::remember(
            static::class.'@all',
            config("Udemy.cache.timeout"),
            function () use ($instance) {
                $domains = Domain::all();
                $links   = collect();

                foreach ($domains as $domain) {
                    $_links = $instance->where(['domain_id' => $domain->id])->get();
                    $links  = $links->merge($_links);
                }

                return $links->all();
            }
        );
    }

    public function get($path = null)
    {
        $result = parent::get($path); // TODO: Change the autogenerated stub

        return is_array($result) && isset($result['links']) ? $this->hydrate($result['links']) : $this->hydrate([$result]);
    }

    public static function findByDomainAndPath($domain, $path)
    {
        return static::all()->filter(
            function ($link) use ($domain, $path) {
                return $link->path === $path && $domain === $link->domain->hostname;
            }
        );
    }

    public function course()
    {
        if ( ! $this->course) {
            if ($this->CourseId) {
                return $this->course = Course::find($this->CourseId);
            }
        }

        return $this->course;
    }
}
